---
- name: check mandatory variables
  fail:
    msg: 'variable {{ mandatory_var.key }} is not defined'
  when: not mandatory_var.value
  loop: "{{ mandatory_vars | dict2items }}"
  loop_control:
    loop_var: mandatory_var

- name: auto login user registry entry
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultUserName
    data: "{{ auto_login_user }}"
    type: string

- name: auto login password registry entry
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: DefaultPassword
    data: "{{ auto_login_user_password }}"
    type: string

- name: auto login registry entry
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
    name: AutoAdminLogon
    data: 1
    type: dword
